# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timetravel < Formula
  desc ""
  homepage "https://github.com/marianina8"
  version "1.0"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Darwin_x86_64.tar.gz"
      sha256 "e7f76c213fc24becc524a373f93f4db2898bcb50fa800b7376af6e7ec8d496d2"

      def install
        bin.install "timetravel"
      end
    end
    on_arm do
      url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Darwin_arm64.tar.gz"
      sha256 "d6cba21af84c7eef5a93b7f630a2354453b61dcb99b60b9395c91baa1f024032"

      def install
        bin.install "timetravel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Linux_x86_64.tar.gz"
        sha256 "a0d77d36ce06735d45ab8bdcf2cfcb0e9986aebb32748bf434eead81fd9b6cf4"

        def install
          bin.install "timetravel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Linux_arm64.tar.gz"
        sha256 "03665facd1a0ded94d9bb7c9b9913b47bf66b6973f4f0b3063d778d65d85820b"

        def install
          bin.install "timetravel"
        end
      end
    end
  end
end
