# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timetravel < Formula
  desc ""
  homepage "https://github.com/marianina8"
  version "1.0.0-beta"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/timetravel/releases/download/1.0.0-beta/timetravel_Darwin_x86_64.tar.gz"
      sha256 "d96af294dd819ca4752d04b8237fe184a5ebe044c76e9c75d823ec9d66e31ad6"

      def install
        bin.install "timetravel"
      end
    end
    on_arm do
      url "https://github.com/marianina8/timetravel/releases/download/1.0.0-beta/timetravel_Darwin_arm64.tar.gz"
      sha256 "18553bb1591b355fdf9a27f567a0f361d12ca57a64474e894da6b9ba490cab32"

      def install
        bin.install "timetravel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/timetravel/releases/download/1.0.0-beta/timetravel_Linux_x86_64.tar.gz"
        sha256 "8816ce1d0ed5b8db1725131225309a7b2e17a62b6a2040241b0128f0a143defc"

        def install
          bin.install "timetravel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/timetravel/releases/download/1.0.0-beta/timetravel_Linux_arm64.tar.gz"
        sha256 "52b622bc5e7818305bbd7f1053643ad2be81421fede2d1460d4173ec8b34d97a"

        def install
          bin.install "timetravel"
        end
      end
    end
  end
end
