# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timetravel < Formula
  desc ""
  homepage "https://github.com/marianina8"
  version "1.0"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Darwin_x86_64.tar.gz"
      sha256 "ad2883deabac56561a430ddf02b9ef49d088f42ae878504f208711c068e33983"

      def install
        bin.install "timetravel"
      end
    end
    on_arm do
      url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Darwin_arm64.tar.gz"
      sha256 "d62fe7aafb77105eee78fd797fa99245e7e95e7a7c1ccdf50db18368c50e957d"

      def install
        bin.install "timetravel"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Linux_x86_64.tar.gz"
        sha256 "78a60baef4124cb249b3be9b329f74b1bd2b4a5f1da6bb43c0dc11dd89c0b5ad"

        def install
          bin.install "timetravel"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/timetravel/releases/download/1.0/timetravel_Linux_arm64.tar.gz"
        sha256 "60baeac63147980ba4601c38a613e23a23fc090e3fe66ed912e7ef3c2cd76161"

        def install
          bin.install "timetravel"
        end
      end
    end
  end
end
